[package]
name = "spherenet-admin"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Sphere-Foundation/spherenet-admin"
license-file = "LICENSE"
readme = "README.md"
description = "Command-line tool for SphereNet governance and network administration"
publish = true

[dependencies]
borsh = { version = "1.5" }
clap = { version = "4.5", features = ["derive"] }
eyre = { version = "0.6" }
serde_json = { version = "1.0" }
sha2 = { version = "0.10" }
solana-client = { version = "2.2.1" }
solana-sdk = { version = "2.2.1" }
spherenet-authority = { version = "=0.1.0" }
spherenet-monetary-policy-client = { path = "../monetary-policy/clients/rust" }
spherenet-monetary-policy-interface = { path = "../monetary-policy/interface", features = [ "solana-p" ] }
spherenet-program-whitelist-client = { version = "=0.1.3" }
spherenet-program-whitelist-interface = { version = "=0.1.3", features = [ "solana-p" ] }
spherenet-validator-whitelist-client = { version = "=0.1.2" }
spherenet-validator-whitelist-interface = { version = "=0.1.2", features = [ "solana-p" ] }
spherenet-whitelisted-loader-v3-interface = { version = "=0.1.0", features = ["bincode"] }
