[package]
name = "spherenet-admin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eyre = { version = "0.6" }
solana-client = { version = "2.2.1" }
solana-sdk = { version = "2.2.1" }
spherenet-program-whitelist-interface = { version = "=0.1.2", features = [ "solana-p" ] }
spherenet-validator-whitelist-interface = { version = "=0.1.2", features = [ "solana-p" ] }
spherenet-validator-whitelist-client = { version = "=0.1.2" }
